export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://halsokostkollen.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/vitaminer","priority":"0.8","changefreq":"weekly"},{"path":"/kosttillskott","priority":"0.8","changefreq":"weekly"},{"path":"/vegansk","priority":"0.8","changefreq":"weekly"},{"path":"/sport","priority":"0.8","changefreq":"weekly"},{"path":"/online","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/apotea-vs-apotek-hjartat","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotea-vs-kronans-apotek","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotea-vs-lloydsapotek","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotea-vs-meds","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotea-vs-apoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotek-hjartat-vs-kronans-apotek","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotek-hjartat-vs-lloydsapotek","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotek-hjartat-vs-meds","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apotek-hjartat-vs-apoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/kronans-apotek-vs-lloydsapotek","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/kronans-apotek-vs-meds","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/kronans-apotek-vs-apoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lloydsapotek-vs-meds","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lloydsapotek-vs-apoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/meds-vs-apoteket","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-23</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }